repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.30.1
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        exclude: __init__.py
        args: ["--application-directories", "src"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
        - "--max-line-length=94"
        additional_dependencies:
          - flake8-bugbear
          - flake8-implicit-str-concat
