# Generated by Django 4.0.6 on 2022-07-29 10:33
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangoproject",
            name="description",
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="djangoproject",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 7, 29, 10, 32, 49, 671010),
                verbose_name="Published in ",
            ),
        ),
    ]
