# Generated by Django 4.0.6 on 2022-07-29 10:34
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_djangoproject_description_alter_djangoproject_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="djangoproject",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 7, 29, 10, 34, 4, 795050),
                verbose_name="Published in ",
            ),
        ),
    ]
